#!/bin/bash

        #---------------------------------------------------#
        #               Functions I use frequently          #
        #                                   -ppurka         #
        #---------------------------------------------------#

        #--------------------- Changelog -------------------#
        # 10/09/2011:   Append -u low to e-notify-send      #
        # 09/03/2011:   Make finding icons more "clever."   #
        #               Cleanups.                           #
        # 02/05/2011:   Stupid POSIX stuff. Make it bash    #
        # 09/25/2009:   First version to have it as a dash  #
        #---------------------------------------------------#

# This calls the dbus interface of e17. The options provided on the command
# line is actually appended directly to the command in the function as:
# dbus-send ..... org.enlightenment.wm."$@"
# e_restart <Core>/<Module>/<Profile>.<function>
e_remote() {
    local DBUS="dbus-send --print-reply=literal \
        --dest=org.enlightenment.wm.service \
        /org/enlightenment/wm/RemoteObject org.enlightenment.wm."
    local QDBUS="qdbus org.enlightenment.wm.service \
        /org/enlightenment/wm/RemoteObject org.enlightenment.wm."
    case "$1" in
        Module.List)    $DBUS$@ ;;
        *)  $QDBUS$@ ;;
    esac
}

# Usage: get_icon [icon_name[.extension]]
get_icon() {
    local icon=""
    if [[ "$1" = *.png || "$1" = *.svg ]]; then
        icon="$( locate -H -l 1 -q --regex "$1$" )"
    elif [[ "$1" ]]; then
        icon="$( locate -H -l 1 -q --regex "$1.(png|svg)$" )"
    fi
    if [[ "$icon" ]]; then
        echo "$icon"
    else
        echo "/usr/share/enlightenment/doc/enlightenment.png"
    fi
}


# Usage: show_passive <heading> <text> [<time in seconds>] [<icon>]
# <icon> = icon name with or without extension
# <time> and <icon> are optional arguments the defaults being
# 10sec and e.png respectively
show_passive() {
    local -i timeout=10
    local icon=""
    [[ "$X_USER" ]] || local X_USER="$USER"
    if pgrep -u $X_USER enlightenment > /dev/null 2>&1 && \
        e_remote Module.List | grep -qs 'notification .*1'; then
        [[ "$3" ]] && \
            if test "$3" -gt 0 2> /dev/null; then
                timeout=$3
            else
                icon="$3"
            fi
        timeout=$(( $timeout * 1000 ))
        [[ -z "$icon" && "$4" ]] && icon="$4"
        icon="$( get_icon "$icon" )"
        e-notify-send -u low -t $timeout -i "file://$icon" "$1" "$2<br>" &
    else
        /usr/local/bin/displaymessage --center --passive "$1:
$2" $timeout &
    fi
}

