#!/bin/bash

        #-----------------------------------------------------------#
        #          bash functions I use less frequently.            #
        #                                   -ppurka                 #
        #-----------------------------------------------------------#

        #----------------- License: GPL-3 or later -----------------#
        # Copyright (C) 2007 - 2011  P. Purkayastha                 #
        # Contact: ppurka _at_ gmail _dot_ com                      #
        # This program comes with ABSOLUTELY NO WARRANTY;           #
        # This is free software, and you are welcome to redistribute#
        # it under certain conditions;                              #
        #                                                           #
        # For a brief summary of the license see the file COPYING   #
        # that is distributed with this program.                    #
        #                                                           #
        # For the full text of the license see                      #
        # http://www.gnu.org/licenses/gpl-3.0.html                  #
        #-----------------------------------------------------------#

        #--------------------- Changelog -------------------#
        # 12/26/2011:   License information.                #
        # 10/09/2011:   Append -u low to e-notify-send      #
        # 09/03/2011:   Make finding icons more "clever."   #
        #               Cleanups.                           #
        # 02/05/2011:   Stupid POSIX stuff. Make it bash    #
        # 09/25/2009:   First version to have it as a dash  #
        #---------------------------------------------------#

# This calls the dbus interface of e17. The options provided on the command
# line is actually appended directly to the command in the function as:
# dbus-send ..... org.enlightenment.wm."$@"
# e_restart <Core>/<Module>/<Profile>.<function>
e_remote() {
    local DBUS="dbus-send --print-reply=literal \
        --dest=org.enlightenment.wm.service \
        /org/enlightenment/wm/RemoteObject org.enlightenment.wm."
    local QDBUS="qdbus org.enlightenment.wm.service \
        /org/enlightenment/wm/RemoteObject org.enlightenment.wm."
    case "$1" in
        Module.List)    $DBUS$@ ;;
        *)  $QDBUS$@ ;;
    esac
}

# Usage: get_icon [icon_name[.extension]]
get_icon() {
    local locate="$(which locate)"
    local extra_args="-H -q"
    if [[ "$(readlink -f $locate)" = */plocate ]]; then
        extra_args=""
    fi

    local icon=""
    if [[ "$1" = *.png || "$1" = *.svg ]]; then
        icon="$( locate ${extra_args} -l 1 --regex "$1$" )"
    elif [[ "$1" ]]; then
        icon="$( locate ${extra_args} -l 1 --regex "$1.(png|svg)$" )"
    fi
    if [[ "$icon" ]]; then
        echo "$icon"
    else
        echo "/usr/share/enlightenment/doc/enlightenment.png"
    fi
}


# Usage: show_passive <heading> <text> [<time in seconds>] [<icon>]
# <icon> = icon name with or without extension
# <time> and <icon> are optional arguments the defaults being
# 10sec and e.png respectively
show_passive() {
    local -i timeout=10
    local icon=""
    if [[ "$DISPLAY" ]]; then
        [[ "$3" ]] && \
            if test "$3" -gt 0 2> /dev/null; then
                timeout=$3
            else
                icon="$3"
            fi
        timeout=$(( $timeout * 1000 ))
        [[ -z "$icon" && "$4" ]] && icon="$4"
        icon="$( get_icon "$icon" )"
        notify-send -u low -t $timeout -i "file://$icon" "$1" "$2<br>" &
    else
        /usr/local/bin/displaymessage --center --passive "$1:
$2" $timeout &
    fi
}

